### PR TITLE
Break down readme into individual docs

### PR DESCRIPTION
**Pull request by Tomcli**
- Break down main readme into individual docs.
- Updated broken links. 
- Added rate limit for Istio.
- change cf commands to bx (added note for user who wants to use cf commands)

### CODE REVIEW

**Comment by Tomcli** [comment]
We decided not to break down the readme.

**Comment by Tomcli** [comment]
conflicts resolved

**Comment by animeshsingh** [comment]
Also please ensure you are using gitignore to remove files like ds_store which are coming in PR

**Comment by Tomcli** [comment]
Created a new PR #8 from a new branch to split readme part B and remove ds_store.

**Pull request closed without merging**
